task1/urls.py
from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/',include('tasks.urls'))
]

tasks/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("",views.index,name="index"),
    path("add",views.add,name="add")
]

tasks/models.py
from django.db import models

# Create your models here.

tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

# tasks = []

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    # priority=forms.IntegerField(label="Priority",min_value=1, max_value=10 )

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"]= []

    return render(request,'tasks/index.html',{
        "tasks" : request.session['tasks']
    })

def add(request):
    if request.method=='POST':
        form = NewTaskForm(request.POST)
        if form.is_valid() :
            task = form.cleaned_data['task']
            # tasks.append(task)
            request.session['tasks'] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request,'tasks/add.html',{
                "form": form
            })
        
    return render(request,'tasks/add.html',{
        'form' : NewTaskForm()
    })

templates/tasks/add.html
{% extends "tasks/layouts.html" %}
{% block title %} Add task{% endblock title %}
{% block body %}
<div class="container">
<h1>Add task</h1>
<br>
        <form submit="{% url 'tasks:add'%}" method="post">
            {% csrf_token %}
            {{form}}
            <br>
            <input type="submit">
        </form>
<br>
<br>
        <a href="{% url 'tasks:index'%}">Go to all tasks </a>
    </div>
{% endblock body %}


{% comment %} <!doctype html>
<html>
    <head>
        <title>Tasks</title>
    </head>
    <body>
        <h1>Add task</h1>
        <form>
            <input type="text" name="task">
            <input type="submit">
        </form>
    </body>
</html> {% endcomment %}

templates/tasks/index.html
{% extends "tasks/layouts.html" %}

{% block title %}
Tasks
{% endblock title %}

{% block body %}
<ul>
     <h2>Tasks</h2>
    {% for task in tasks %}
        <br>
        <li>{{task}}</li>
    {% empty %}
        <li>No Tasks</li>
    {% endfor %}
    <br><br>
    <a href="{% url 'tasks:add' %}">Add a New Task </a>
</ul>
 {% endblock body %}
 
 
 {% comment %} <html>
    <!doctype html>
    <head>
        <title>Tasks</title>
    </head>
    <body>
        <ul>
            {% for task in tasks %}
            <li>{{task}}</li>
            {% endfor %}
        </ul>
    </body>
</html> {% endcomment %}

templates/tasks/layouts.html
<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body>
        {% block body %}{% endblock body %}
    </body>
</html>